services:
  - type: web
    name: poto-timide
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: SESSION_SECRET
        generateValue: true
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false